name = "edgetunnel"
pages_build_output_dir = "."
compatibility_date = "2025-11-04"
keep_vars = true

[[kv_namespaces]]
binding = "KV"
id = "edd4f114cc344a47a49a96807fa888a9"

[[env.preview.kv_namespaces]]
binding = "KV"
id = "edd4f114cc344a47a49a96807fa888a9"
